- pyproject.toml
- seagoat/main.py
> feat: remove interactive mode

- seagoat/sources/chroma.py
- tests/__snapshots__/test_chroma.ambr
- tests/__snapshots__/test_server.ambr
- tests/conftest.py
- tests/test_chroma.py
> perf: avoid wasting time processing irrelevant results

- seagoat/cli.py
- tests/conftest.py
- tests/test_cli.py
> feat: show a warning when SeaGOAT is outdated

- README.md
Sorry for the small edit, got annoying when I was installing this.
> Fix URL for Bat Dependency in README

- README.md
fixing typo about Operating Systems
> fix: Readme typo in Operating Systems

- seagoat/sources/chroma.py
- tests/test_chroma.py
> fix: avoid crashing when file no longer exists

- seagoat/engine.py
- tests/test_ripgrep.py
> fix: don't crash when ripgrep finds an uncached file

- README.md
- docs/server.md
- seagoat/cache.py
- seagoat/server.py
- tests/test_server.py
> feat: include cache folders in server info JSON

- README.md
- docs/configuration.md
- seagoat/cli.py
- seagoat/utils/config.py
- tests/test_cli.py
- tests/test_config.py
> feat: allow cli to connect to a remote server

- seagoat/cli.py
- seagoat/utils/cli_display.py
- tests/__snapshots__/test_cli.ambr
- tests/conftest.py
- tests/test_cli.py
> fix: display files correctly when remote server is divergent

- seagoat/file.py
Speed up initial scan by exiting from the loop early if the line contains more than 3 alphanumerical characters.
<details><summary>Measurements</summary>
<p>
Codebase: [SerenityOS](https://github.com/SerenityOS/serenity)
Hardware: MacBook Pro 14" (M1 Pro)
```
2023-10-07 19:54:33,337 Creating server...
2023-10-07 19:54:33,338 Starting worker thread...
2023-10-07 19:54:33,340 Serving on http://0.0.0.0:53385
2023-10-07 19:54:33,753 Checking repository for new changes
Analyzing source code: 0it [00:00, ?it/s]
2023-10-07 19:54:46,419 Analyzed the minimum number of chunks needed to operate. 
2023-10-07 19:54:46,419 Note, 835884 chunks need to be analyzed for optimum performance.
```
13.082 sec before minimum number of chunks is analyzed
```
2023-10-07 20:02:01,040 Creating server...
2023-10-07 …
```
> Speed up initial minimal analysis by ≈25%

- docs/configuration.md
Docs change to include example of how a user would set execution provider for ONNX
> Docs_chroma_embedding_function

- docs/configuration.md
- docs/developer.md
- docs/server.md
Update docs: fix typo, some text improves.
> Update docs: fix typo, some improves.

- README.md
esimation -> estimation  in FAQ section
> Update README.md - Fix a typo

- .github/workflows/test.yml
- seagoat/cache.py
- seagoat/engine.py
- seagoat/gitfile.py
- seagoat/repository.py
- seagoat/result.py
- seagoat/sources/chroma.py
- seagoat/sources/ripgrep.py
- seagoat/utils/file_reader.py
- tests/__snapshots__/test_cli.ambr
- tests/__snapshots__/test_server.ambr
- tests/conftest.py
- tests/test_chroma.py
- tests/test_file.py
- tests/test_json_serialization.py
- tests/test_regexp.py
- tests/test_result.py
- tests/test_result_sorting.py
- tests/test_ripgrep.py
- tests/test_server.py
- tests/test_source_ripgrep.py
fixes #226
partially addresses https://github.com/kantord/SeaGOAT/issues/256
> feat: store different versions of the same file

- seagoat/cli.py
- seagoat/server.py
- tests/conftest.py
- tests/test_cli.py
> feat: allow POST queries

- .pre-commit-config.yaml
- docs/server.md
- seagoat/cache.py
- seagoat/server.py
- seagoat/sources/ripgrep.py
- tests/__snapshots__/test_server.ambr
- tests/conftest.py
- tests/test_server.py
> feat: add endpoint to query files

- seagoat/server.py
- seagoat/utils/server.py
- tests/test_server.py
> feat: explicitly fail when git repo not found

- .github/workflows/frizbee.yml
This PR adds the open source Frizbee action to the repository.
> Adds Frizbee Action

- seagoat/cli.py
- tests/__snapshots__/test_cli.ambr
- tests/test_cli.py
Hello there, decided to get this first issue!
I hope it really that simple, and we don't need anything else...
Refs #610
> feat: Add --reverse option

- seagoat/engine.py
- seagoat/repository.py
- tests/conftest.py
- tests/test_queue.py
- tests/test_repository.py
Process only files returned by `git ls-files`.
Refs #711
> fix: Fix processing files from .gitignore
